name: Update JSON from Google Sheet

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install gspread oauth2client

      - name: Create creds.json
        run: echo "${{ secrets.GSHEET_CREDS }}" > creds.json

      - name: Run export script
        env:
          SHEET_ID: 1Ybm5OiBXGlo8gOOcfJzAxHddytnRJH5LrCnkaew1eq4
          SHEET_NAME: Sheet1
        run: python google_sheet_to_json.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json
          git commit -m "Update data.json" || echo "No changes to commit"
          git push
